"""Draft Chapter 6 main-tail rows 80--159; preview before writing."""
import argparse, json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[5] / 'tools'))
from chapter_source_014 import load
OUT=Path(__file__).with_name('slice_0080.targets.json')
TEXT=["Hehe... I came", "to see your face...", "What?!", "?!", "...", "Just kidding.", "Kunon asked me", "to deliver a message.", "That person you saved", "can finally", "speak now.", "Really?!", "I'm glad...", "...", "But...", "Is something wrong?", "Come see him", "once. He'll give you", "the details.", "Understood.", "After this child's lesson,", "I'll definitely come by.", "Understood.", "After this child's lesson,", "I will definitely come.", "Oh, Teacher!", "You came at just", "the right time.", "What's wrong?", "Scarrel.", "Is something wrong?", "Scarrel?", "So, tonight's side dish:", "what do you want to eat?", "Huh?", "What?", "We take turns cooking,", "and today's my turn,", "but...", "I'm out of menu ideas,", "so I thought I'd borrow", "your wisdom.", "What I want to eat...", "Something I want", "to eat...", "In that case...", "　Nothing in particular.", "　A full Imperial meal.", "　I can't think of anything.", "　All dessert.", "Nothing in particular.", "Hmm...", "I can't think of anything.", "Hmm, that makes", "it difficult.", "Even if you say that...", "The food on this island", "is unusual, so cooking it", "is different from in the Empire...", "Rather than ask me,", "maybe learn from", "the islanders?", "Even if you say that,", "I'm at a loss too.", "You see, the food on this island", "is unusual, so cooking it", "differs from the Empire...", "Rather than ask me,", "maybe learn from", "the islanders?", "Ah, I see!", "That's an idea.", "All right, later", "I'll ask", "everyone in the village. ♪", "Speaking of which, in etiquette class", "we had a full course", "of Imperial cuisine...", "That was delicious.", "Could that be"]
def build():
 rsrc,rows,_=load(180);start=4037;assert len(TEXT)==80;trans={}
 for rel,text in enumerate(TEXT):
  p=start+rel;row=rows[p];trans[row['id']]={'id':row['id'],'source_sha256':row['source_sha256'],'source_offset':row['source_offset'],'source_byte_length':row['source_byte_length'],'reference_instructions':row['reference_instructions'],'resource_row':80+rel,'physical_ordered_index':p,'text':text,'status':'draft','notes':'Self-checked draft; physical rows 4017-4136 examined for scene and branch context. Pending independent meaning review.'}
 return {'resource_id':rsrc['id'],'section':'main-tail','assigned_range':[80,159],'physical_ordered_index_range':[4037,4116],'rows_examined':{'ranges_inclusive':[[4017,4136]],'count':120},'translations':trans}
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');a=p.parse_args();d=build();print(json.dumps({'mode':'write' if a.write else 'dry-run','resource_id':d['resource_id'],'rows':len(d['translations']),'sample':list(d['translations'].values())[:3]},ensure_ascii=False,indent=2));a.write and OUT.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
