"""English-only author draft for battle-event ordered rows 240-319."""
import argparse
from battle_pass_055 import save

LINES = [
    "we'll crush them all at once!", # 240
    "All right!",
    "Now...",
    "We did it!",
    "Now...",
    "Why did you leave the organization?",
    "Someone as skilled as you...",
    "Because I was a coward...",
    "That's all.",
    "I've got nothing left...",
    "I've got nowhere...",
    "nowhere left to goooo!!",
    "Vijue... How pitiful...",
    "I can't bear to watch...",
    "Your suffering is written",
    "all over you.",
    "Is this the ultimate act of self-torment?",
    "Ahahaha! It's not even funny!!",
    "Here I come, Ordreik!",
    "I'm going to stop you,",
    "no matter what!!",
    "Ordreik!",
    "I will stop you,",
    "no matter what!!",
    "Lend me your strength!",
    "Let's unite our hearts",
    "and defeat Ordreik!",
    "Lend me your strength!",
    "Let's unite our hearts",
    "and defeat Ordreik!",
    "Then show me...",
    'your "answer"!',
    "This is my answer...",
    "the answer I fought to find!!",
    "This is my answer...",
    "with all my heart and soul!!",
    "Quite the disguise you've put on.",
    "But without the substance to match,",
    "you can't even pass for a clown!",
    "You're the laughable one!",
    "Let the name Ordreik Servolt",
    "be etched into your heart with terror!!",
    "Get away from my husband!",
    "You impostor!!",
    "What are you talking about?",
    "He's always been mine!",
    "I'll bring it all to an end...",
    "To make my wish come true,",
    "there's no longer...",
    "any other way",
    "left for me!",
    "Aaaaaah!!!!",
    "I'll give you all the magic you need!",
    "Answer my summons, demons!",
    "Destroy every last thing!!!",
    "I won't let you do that!",
    "I won't allow that!",
    "Why... Why...?",
    "Where did I go wrong...?",
    "...Huh?",
    "If only you...",
    "If only you...",
    "had never existed!!!",
    "Ishlar...",
    "Hurting others and getting hurt...",
    "It really was foolish, wasn't it?",
    "It only made the pain worse.",
    "Ahahahahaha...",
    "Shut up... Shut uuuuup!!!",
    "You shall know our suffering...",
    "Our grief! Our rage!!",
    "Feel it all!!!",
    "I can feel it...",
    "The rage and grief of the spirits",
    "you have defeated...",
    "That is what gave me form!!",
    "You who can do nothing but hurt each other",
    "cannot defeat me!!",
    "And you... have no right",
    "to exist in this world!!", # 319
]

if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');a=p.parse_args()
    save(240,LINES,[[232,328]],
         uncertainties=[
             {'rows':[245,248],'note':'The organization is unnamed here; retain generic organization rather than infer its name.'},
             {'rows':[276,281],'note':'Matching speaker operands and hostile mirror replies suggest a mimic/disguise exchange; disguise keeps the appearance-versus-substance taunt without asserting the mechanism.'},
             {'rows':[292,294],'note':'The invocation does not mark number; demons follows the broad summoned threat without assigning gender.'},
             {'rows':[304,306],'note':'The speaker/link to a past self is not conclusively decoded. It really was foolish retains a grammatical impersonal judgment instead of inventing I/you/we.'},
         ],
         omissions=[
             {'rows':[241,244],'note':'Now... remains a deliberate unfinished result after a victory exclamation.'},
             {'rows':[286,291],'note':'The incomplete first box runs directly into the next box; together the speaker has no other way left to fulfill the wish.'},
             {'rows':[304,306],'note':'Identity of who hurt others remains unassigned; English has impersonal subject It and retains the reciprocal hurt and retrospective judgment.'},
         ],
         notes='Read whole VM groups and adjacent slices. Row240 joins agreed root row239. Nonempty fragments preserve the battle compiler structure. Character spellings follow current overlay. Independent review required.',
         write=a.write)
