"""English-only author draft for battle rows560-639; never self-accept."""
import sys
from battle_pass_055 import save

lines = [
    "Wouldn't that leave you",
    "more beaten up than lovestruck?",
    "Ahahaha...",
    "They sure blend right",
    "into the scenery!",
    "Those accursed monsters...",
    "Please be safe,",
    "Phlaiz...",
    "So the enemy can use summon magic too?",
    "Then... everyone!",
    "Be especially wary of Berserk Summoning!!",
    "I doubt those creatures",
    "have any sense of restraint...",
    "I should think not...",
    "Oh, no, Yukres Village...",
    "Beardy and the others...",
    "Don't worry, Marurur.",
    "Jakini's tougher",
    "than he looks.",
    "They'll hold out",
    "until we get there!",
    "A barrel of gunpowder, eh...?",
    "Hmm, if I can put that",
    "to good use... Heheheh.",
    "You're cooking up another",
    "underhanded scheme to win",
    "by cheating, aren't you?",
    "Wahahaha! A smashing success!!",
    "Let's keep pushing through",
    "all the way to the back!!",
    "Let's keep pushing through",
    "all the way to the back!!",
    "All riiight!!",
    "What is this",
    "awful feeling...?",
    "My sense of dread",
    "just keeps getting worse...",
    "I can't stop shaking...",
    "Impossible! How could I...!?",
    "It's impossible...",
    "But there's no mistaking it!",
    "Could it be...?",
    "It can't be...",
    "But there's no mistaking it!",
    "Could it be...?",
    "Dielgo... We won't succumb",
    "to the fate you would",
    "force upon us...",
    "As a Lawler...",
    "I swear on the name",
    "of Magna Clesment...",
    "We will never",
    "give up,",
    "right to the very end!!!!",
    "Dielgo... We won't succumb",
    "to the fate you would",
    "force upon us...",
    "As a Lawler...",
    "I swear on the name",
    "of Toris Clesment...",
    "We will never",
    "give up,",
    "right to the very end!!!!",
    "That thing called itself",
    "Dielgo.",
    "If that wasn't",
    "just a bluff,",
    "then could it...!?",
    "The Seat of Core Cognizance is a device",
    "that draws enormous amounts of magic",
    "from Clyps...",
    "If this creature",
    "has learned to harness it,",
    "then...!?",
    "A new Dielgo...",
    "If that's true,",
    "then this enemy can also draw",
    "endless power from Clyps...!?",
    "Dielgo of Primal Sin...",
    "If it has complete control", # 639; joins640-641
]

if __name__ == '__main__':
    save(560, lines, [(551,641)],
         uncertainties=[
             {'rows':[560,561,562], 'decision':'Rendered source sound-play about swooning versus being battered as lovestruck versus beaten up, retaining the joke without inventing another action.'},
             {'rows':[570,571,572], 'decision':'Berserk Summoning is provisional English gameplay terminology approved by orchestrator after mechanics research.'},
             {'rows':[608,617], 'decision':'Lawler title confirmed by orchestrator terminology research; Magna Clesment/Toris Clesment use existing gallery-based glossary.'},
             {'rows':[628,629,630], 'decision':'Seat of Core Cognizance approved by orchestrator, combining established Core Cognizance with source seat/throne suffix.'},
             {'rows':[638], 'decision':'Dielgo of Primal Sin approved as provisional epithet by orchestrator, matching existing Shadow of Primal Sin glossary.'},
         ],
         omissions=[
             {'rows':[574,575], 'reason':'Alarmed trailing phrases deliberately leave the threat unsaid, as in source.'},
             {'rows':[581,582,583], 'reason':'Kyle leaves the gunpowder scheme unfinished before laughing.'},
             {'rows':[597,598], 'reason':'Speaker trails off in disbelief after explicit shaking sentence.'},
             {'rows':[599,600,601,602,603,604], 'reason':'Both player variants leave sensed identity unspoken; preserved questioning suspense instead of guessing referent.'},
             {'rows':[625,626,627], 'reason':'Speaker trails off before specifying the feared consequence.'},
             {'rows':[631,632,633], 'reason':'Conditional consequence deliberately unfinished; kept trailing then.'},
         ],
         notes='Read complete VM groups551-641;640-641 are in own final slice. No gender inferred for unknown enemy. All names follow current glossary. Independent review required.',
         write='--write' in sys.argv)
