"""English-only author draft for battle-event ordered rows 320-399."""
import argparse
from battle_pass_055 import save

LINES = [
    "Those two pillars", # 320
    "are the control devices for the Clyps!",
    "If we can destroy them,",
    "we should be able to",
    "seal Dielgo's power...!",
    "A barrier against physical attacks",
    "and another against magic, huh...?",
    "More of those damn troublesome",
    "defensive barriers are up.",
    "Even so!",
    "With everyone's strength...",
    "we'll get it done!!",
    "Even so!",
    "With everyone's strength...",
    "we will see it through!!",
    "...!!",
    "Defeating that thing",
    "weakened the barrier!?",
    "Yes... I'm sure we must",
    "break down the defensive barriers that way",
    "before we can do any damage at all!",
    "That last attack seems to have",
    "weakened the barrier against physical attacks!",
    "Now, while we have the chance!",
    "That last attack seems to have",
    "weakened the barrier against magic...",
    "Now's our chance to strike!",
    "That last attack weakened the barrier!",
    "But...",
    "This one can only be hurt by weapons",
    "and physical attacks. And...",
    "it looks like only summon magic",
    "will work on this one!",
    "Listen, everyone.",
    "I'll tell you what I've learned",
    "about breaking down the barriers.",
    "Defeating the red enemies",
    "weakens the red core's barrier",
    "against physical attacks...",
    "And defeating the green enemies",
    "weakens the green core's barrier",
    "against magic.",
    "The purple enemies will probably",
    "weaken both barriers when defeated.",
    "I see...!",
    "All right, everyone, let's go!!",
    "Yes, I understand!",
    "...!!",
    "It seems concentrating all our attacks",
    "on just one of them is dangerous.",
    "If we carelessly make it lose control,",
    "its magic will run wild",
    "and we'll have no way to stop it...!",
    "We must damage both pillars evenly",
    "and destroy them as close together as possible.",
    "It won't be easy...",
    "but we have no other choice!!",
    "Right!!",
    "That's right!",
    "Let's go, everyone!",
    "!?",
    "What is this awful feeling...?",
    "This is bad!!",
    "Everyone, get away from that thing!!",
    "!?",
    "What is this awful feeling...?",
    "Oh, no!!",
    "Everyone, run!!",
    "Uooooooooh",
    "aaaaaah!!!!",
    "What hideous magic...",
    "You monster...!",
    "...But that is precisely",
    "what makes it",
    "worth obtaining!",
    "......",
    "Az... li...",
    "I'm... sor...",
    "S-stay away!",
    "You monster!!", # 399
]

if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');a=p.parse_args()
    save(320,LINES,[[312,407]],
         uncertainties=[
             {'rows':[320,321],'note':'Clyps uses the existing provisional project spelling from story_core_terms and chapter17_terms; it is not claimed to be an official English term.'},
             {'rows':[349,352],'note':'This one appears to accompany an onscreen selection/camera cue. Both demonstratives remain this one, with distinct physical/summon magic restrictions preserved.'},
             {'rows':[370,374],'note':'The context supplies control devices as the subject. Even damage followed by destruction as close together as possible preserves the simultaneous-pillar mechanic.'},
             {'rows':[396,397],'note':'The protagonist is voicing a broken Azlier name and apology. Az... li... and I am sor... retain the interrupted utterance rather than complete the name/apology.'},
         ],
         omissions=[{'rows':[396,397],'note':'The name and apology remain deliberately interrupted, reflecting failing speech. The English apology restores I rather than leaving a subjectless complete assertion.'}],
         notes='Read adjacent whole VM groups. Current Clyps/Dielgo project spellings applied. Mechanical restrictions retained without shortening. Independent review required.',
         write=a.write)
