"""English-only author draft for battle-event ordered rows 400-479."""
import argparse
from battle_pass_055 import save

LINES = [
    "Answering violence with still more violence...", # 400
    "So in the end, that was the only answer",
    "you could find...",
    "If you want to stop me,",
    "then get serious, Kunon!",
    "If you want to stop me,",
    "then you had better get serious,",
    "Kunon!",
    "Uaaaah!!",
    "Her body really is",
    "in terrible condition...",
    "If she keeps running out of control,",
    "she'll crash",
    "before long...!",
    "What!?",
    "Then we have to hurry!",
    "(...But if I'm not careful",
    "to hold back as I fight,",
    "Kunon's body won't hold out...)",
    "Kunon...",
    "Lady Ardylia...",
    "Forgive me...",
    "Another me...",
    "I really have broken down",
    "completely, haven't I...?",
    "My former self...",
    "I will correct my mistakes",
    "with my own hands!",
    "Our lives, our pride...",
    "On those who defile them...",
    "Let the curse of death fall!!",
    "Let the curse of death... fall!!",
    "Eeeek!",
    "Y-you don't have to keep saying it!",
    "I heard you!",
    "We must destroy the unit.",
    "Otherwise, the damage",
    "will only continue to spread.",
    "...!",
    "...Here I go!!",
    "Biocomponent protection has been damaged.",
    "The erased donor personality",
    "is regenerating as a bug...",
    "Who am I? Who are you??",
    "What is this unit??? Stop...",
    "Give me back my bodyyyy!!",
    "You spout such childish nonsense",
    "with such arrogance...",
    "I'll silence you for good",
    "so you can never speak",
    "like that again!!",
    "You'd involve yourself",
    "in the cursed fate",
    "of my older sister and me...",
    "Do you want to be cursed too?",
    "That curse...",
    "I'll cast it aside!",
    "That curse...",
    "I will overcome it!",
    "Ishlaaar!!",
    "Yes...",
    "That's the way,",
    "that's...",
    "Let's go, you lot!",
    "This is waaaaar!!",
    "Wahahaha, you fools!",
    "This place is as familiar to us",
    "as our own backyard!!",
    "Now we'll teach you that",
    "the painful way!!",
    "Gahahaha! That'll teach you!",
    "A victory for my brilliant mind!",
    "Everyone!",
    "Let's get them!!",
    "Graaaaah!!",
    "It looks like that girl Marurur",
    "is egging everyone",
    "on.",
    "It looks like that girl Marurur",
    "is egging everyone", # 479, next author's480 is on.
]

if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('--write',action='store_true');a=p.parse_args()
    save(400,LINES,[[392,487]],
         uncertainties=[
             {'rows':[400,402],'note':'You is supplied from the preceding berserk protagonist scene; the speaker condemns the protagonist responding with escalating violence.'},
             {'rows':[409,418],'note':'Kunon is established by name in adjacent groups, and glossary story_context_part_c documents female identity; her is grounded there. The unfinished body warning is rendered as wont hold out, the implied danger stated just above.'},
             {'rows':[422,427],'note':'The mirror dialogue explicitly identifies another me and former self; no mimic mechanism is invented.'},
             {'rows':[440,445],'note':'Technical damaged-system report keeps the donor personality and bug; exact hardware speaker identity is not required and no pronoun gender is introduced.'},
             {'rows':[451,458],'note':'Source explicitly says older sister and younger brother. My older sister and me preserves that relationship; you comes from the following direct question.'},
             {'rows':[470,471],'note':'My brilliant mind chooses the boastful speaker as possessor from the preceding territorial taunts; source itself only specifies brilliant brains.'},
         ],
         omissions=[
             {'rows':[428,430],'note':'The first two rows are a suspended curse invocation completed in the next box, with the curse of death as its subject.'},
             {'rows':[460,462],'note':'The final thats... stays unfinished exactly as the fading utterance; no missing predicate is invented.'},
         ],
         notes='Read neighboring whole VM groups. Kunon/Ardylia identity evidence from story_context parts b/c; current name overlay wins aliases. Row479 joins coordinated author_c row480 on. Independent review required.',
         write=a.write)
