"""Draft consecutive English slices for Chapter 2 resource 00:00088."""

import argparse
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, str(Path(__file__).parent))

from chapter_source import chapter_source
from dialogue_encoding import control_tokens


TARGETS_BY_START = {0: {
    0: "Beep, beep.",
    1: "Mmm... ngh...",
    2: "Meow, meow.",
    3: "Mmm... ngh...",
    4: "Bwee, bwee.",
    5: "Mmm... ngh...",
    6: "Kyu, kyuu.",
    7: "Mmm... ngh...",
    8: "...Where am I?",
    9: "Poo-pii...",
    10: "...Where am I?",
    11: "Meow...",
    12: "...Where am I?",
    13: "Bwee...",
    14: "...Where am I?",
    15: "Kyupii...",
    16: "Right...",
    17: "I just",
    18: "fell asleep like that.",
    19: "Ugh...",
    20: "How embarrassing...",
    21: "Wait, where did",
    22: "that guy go!?",
    23: "Right...",
    24: "I fell asleep",
    25: "just like that.",
    26: "...How careless.",
    27: "More importantly, where is that person?",
    28: "C-Could it be that I",
    29: "fell asleep",
    30: "just like that?",
    31: "Ugh...",
    32: "M-More importantly!",
    33: "Where in the world",
    34: "did that person go???",
    35: "Oh no, I...",
    36: "fell asleep",
    37: "just like that...",
    38: "...",
    39: "Ah, Teacher...?",
    40: "Where is Teacher!?",
    41: "Morning.",
    42: "Oh, morning.",
    43: "You're awake already.",
    44: "Beep-beep!",
    45: "Ah...",
    46: "Meow, meow!",
    47: "Ah...",
    48: "Bwee-bwee!",
    49: "Ah...",
    50: "Kyupii!",
    51: "Ah...",
    52: "I looked around",
    53: "for anything useful,",
    54: "you know.",
    55: "I looked around nearby",
    56: "to see",
    57: "if there was anything useful.",
    58: "You were sleeping so soundly,",
    59: "I didn't wake you.",
    60: "You were sleeping so soundly,",
    61: "I thought it might be wrong",
    62: "to wake you...",
    63: "You could have",
    64: "woken me up.",
    65: "Ah, sorry.",
    66: "Sorry.",
    67: "I-In that case,",
    68: "you should ask first",
    69: "before acting!",
    70: "Ah, sorry.",
    71: "Oh, sorry.",
    72: "And, you know? I picked up",
    73: "some weapons and everyday supplies",
    74: "that had washed ashore.",
    75: "And then, I picked up",
    76: "some weapons and everyday supplies",
    77: "that had washed ashore.",
    78: "This is...",
    79: "This is...",
}, 80: {
    80: "This is...",
    81: "This is...",
    82: "Yeah, it must be",
    83: "something from",
    84: "that ship.",
    85: "Yeah, it's probably",
    86: "something that was on",
    87: "that ship.",
    88: "...",
    89: "...",
    90: "...",
    91: "...",
    92: "...Ah.",
    93: "Heh...",
    94: "What's so funny?",
    95: "You're awfully relaxed.",
    96: "Beep beep!",
    97: "...",
    98: "Meow...",
    99: "...",
    100: "Bwee...",
    101: "Heh...",
    102: "S-Sorry!",
    103: "Kyuu...",
    104: "Ha ha ha, come to think of it,",
    105: "we haven't eaten anything",
    106: "since yesterday.",
    107: "All right, first",
    108: "let's get something to eat.",
    109: "Come to think of it,",
    110: "we haven't eaten anything",
    111: "since yesterday, have we?",
    112: "Right, first",
    113: "we need to find",
    114: "something to eat.",
    115: "Huh? But...",
    116: "Huh? But...",
    117: "Huh? But...",
    118: "Huh? But...",
    119: "It's fine, it's fine.",
    120: "Leave it to me.",
    121: "Don't worry.",
    122: "Leave it to Teacher, okay?",
    123: "But I'm glad",
    124: "you washed up",
    125: "on this island too.",
    126: "I kept wondering",
    127: "what I'd do",
    128: "if we'd stayed separated.",
    129: "But I'm really glad",
    130: "you washed up",
    131: "on this island too.",
    132: "But I'm really glad",
    133: "you washed up",
    134: "on this island too.",
    135: "I worried about",
    136: "what I'd do",
    137: "if we'd stayed separated.",
    138: "When I was collapsed on the beach,",
    139: "this little one",
    140: "woke me up.",
    141: "Beep!",
    142: "A stray summoned beast?",
    143: "It seems awfully",
    144: "friendly for one.",
    145: "A stray summoned beast?",
    146: "It seems very",
    147: "friendly for one.",
    148: "Beep???",
    149: "It seemed like",
    150: "it wanted to take me",
    151: "somewhere.",
    152: "On the way...",
    153: "Those summoned beasts",
    154: "attacked it, right?",
    155: "Those summoned beasts",
    156: "attacked it, didn't they?",
    157: "This little one protected me!",
    158: "It did its best, even though",
    159: "it's so small.",
}, 160: {
    160: "So that's why it tried",
    161: "to protect me, even if",
    162: "it had to do something",
    163: "so reckless...",
    164: "So that's why it tried",
    165: "to protect me, even if",
    166: "it had to do something reckless.",
    167: "......",
    168: "...",
    169: "So this little one is",
    170: "your lifesaver, then?",
    171: "",
    172: "So this little one is",
    173: "Nup's lifesaver, then.",
    174: "",
    175: "Then...",
    176: "can I take it with me?!",
    177: "Yeah, of course.",
    178: "Yes, naturally.",
    179: "Ha ha!",
    180: "All right!!",
    181: "Good for you, R.",
    182: "R",
    183: "Beep beep!",
    184: "R?",
    185: "That's its name.",
    186: "Look, it has a big",
    187: "symbol right here, doesn't it?",
    188: "Just because of that...",
    189: "Beep beep!",
    190: "Well, okay.",
    191: "It seems to like it,",
    192: "so...",
    193: "This little one woke me",
    194: "up after I collapsed.",
    195: "",
    196: "Meow!",
    197: "A stray summoned beast?",
    198: "It seems awfully",
    199: "friendly for one.",
    200: "A stray summoned beast?",
    201: "It seems very",
    202: "friendly for one.",
    203: "Meow???",
    204: "It seemed to want",
    205: "to take me somewhere,",
    206: "but...",
    207: "On the way...",
    208: "Those summoned beasts",
    209: "attacked it, right?",
    210: "Those summoned beasts",
    211: "attacked it, didn't they?",
    212: "What a silly little thing.",
    213: "It tried to fight",
    214: "to protect me.",
    215: "So that's why it tried",
    216: "to protect me, even if",
    217: "it had to do something reckless...",
    218: "So that's why it tried",
    219: "to protect me, even if",
    220: "it had to do something reckless.",
    221: "Even I know that was",
    222: "reckless...",
    223: "Isn't it okay?",
    224: "No, it isn't.",
    225: "Huh?",
    226: "You were desperate, weren't you?",
    227: "Thinking about that little one.",
    228: "You were desperate, weren't you?",
    229: "You wanted to protect",
    230: "that little one...",
    231: "Y-Yeah...",
    232: "Then it's fine.",
    233: "Hold your head high.",
    234: "You don't need to apologize.",
    235: "Because you didn't do anything",
    236: "wrong.",
    237: "...",
    238: "All right, next is over there.",
    239: "You two, come on?",
}, 240: {
    240: "All right, next is over there.",
    241: "Shall we go?",
    242: "Meow, meow!!",
    243: "......",
    244: "By the way, does that little one",
    245: "have a name?",
    246: "By the way, does that little one",
    247: "have a name?",
    248: "Teco...",
    249: "Teco?",
    250: "Because that's how",
    251: "it walks.",
    252: "Huh...",
    253: "I see...",
    254: "Nice to meet you,",
    255: "Teco.",
    256: "Meow, meow!",
    257: "This little one woke me",
    258: "up after I collapsed.",
    259: "",
    260: "Bwee!",
    261: "A stray summoned beast?",
    262: "It seems awfully",
    263: "friendly for one.",
    264: "A stray summoned beast?",
    265: "It seems very",
    266: "friendly for one.",
    267: "Bwee???",
    268: "It seemed to want",
    269: "to lead me somewhere,",
    270: "but...",
    271: "On the way...",
    272: "Those summoned beasts",
    273: "attacked it, right?",
    274: "Those summoned beasts",
    275: "attacked it, didn't they?",
    276: "This little one tried",
    277: "to protect me. It did its best",
    278: "even though it's so small...",
    279: "So that's why it tried",
    280: "to protect me, even if",
    281: "it had to do something reckless...",
    282: "I see...",
    283: "But I was still",
    284: "reckless...",
    285: "Isn't it okay?",
    286: "No, it isn't.",
    287: "Huh?",
    288: "You were desperate, weren't you?",
    289: "Thinking about that little one.",
    290: "You were desperate, weren't you?",
    291: "You wanted to protect",
    292: "that little one...",
    293: "Y-Yes...",
    294: "Then it's fine.",
    295: "Hold your head high.",
    296: "You don't need to apologize.",
    297: "Because you didn't do anything",
    298: "wrong.",
    299: "...",
    300: "All right, next is over there.",
    301: "You two, come on?",
    302: "All right, next is over there.",
    303: "Shall we go?",
    304: "Bwee!!",
    305: "W-What!?",
    306: "Don't get so full of yourself...!",
    307: "By the way, does that little one",
    308: "have a name?",
    309: "By the way, does that little one",
    310: "have a name?",
    311: "I call it",
    312: "Onibi.",
    313: "Onibi?",
    314: "It's fine, isn't it?",
    315: "It's a cute name, right?",
    316: "Oh, yeah...",
    317: "Nice to meet you,",
    318: "Onibi.",
    319: "Bwee-bwee!",
}, 320: {
    320: "This little one woke me",
    321: "up when I was unconscious.",
    322: "",
    323: "Kyu!",
    324: "A stray summoned beast?",
    325: "It seems awfully",
    326: "friendly for one.",
    327: "A stray summoned beast?",
    328: "It seems very",
    329: "friendly for one.",
    330: "Kyuu???",
    331: "It seemed to want",
    332: "to take me somewhere,",
    333: "but...",
    334: "On the way...",
    335: "Those summoned beasts",
    336: "attacked it, right?",
    337: "Those summoned beasts",
    338: "attacked it, didn't they?",
    339: "N-No...!",
    340: "This little one did nothing",
    341: "wrong!",
    342: "Whenever I was about to cry,",
    343: "it comforted me",
    344: "and protected me...",
    345: "So that's why it tried",
    346: "to protect me, even if",
    347: "it had to do something reckless...",
    348: "I see...",
    349: "......",
    350: "...",
    351: "So this little one is",
    352: "your lifesaver, then?",
    353: "",
    354: "So this little one is",
    355: "Alieze's lifesaver, then.",
    356: "",
    357: "Then...",
    358: "can I take it with me?!",
    359: "Yeah, of course.",
    360: "Yes, naturally.",
    361: "Good for you,",
    362: "Quiupy.",
    363: "I'm so glad...",
    364: "Kyu-py!!",
    365: "Quiupy?",
    366: "That's this little one's name, but...",
    367: "Um...",
    368: "Is it strange after all?",
    369: "No, I don't think",
    370: "it is.",
    371: "No, I don't think",
    372: "it is.",
    373: "Probably...",
    374: "Kyuu-py!",
    375: "Heave...!",
    376: "Watch your step.",
    377: "There may be something dangerous",
    378: "hidden in the undergrowth.",
    379: "Follow the path",
    380: "I take,",
    381: "okay?",
    382: "Follow the path",
    383: "I take,",
    384: "okay?",
    385: "Okay, I understand.",
    386: "Beep!",
    387: "Hey...",
    388: "Hm?",
    389: "Yesterday, um...",
    390: "Thanks.",
    391: "Ah, you don't have",
    392: "to worry about that.",
    393: "I promised, didn't I?",
    394: "I'd protect you",
    395: "no matter what.",
    396: "Yeah...",
    397: "Besides, I'm",
    398: "your teacher.",
    399: "I can't call myself",
}, 400: {
    400: "a teacher if I can't properly look after",
    401: "my students.",
    402: "You're welcome.",
    403: "But you don't have",
    404: "to worry about that.",
    405: "I was only keeping",
    406: "my promise.",
    407: "Yeah...",
    408: "Besides, I'm",
    409: "your teacher.",
    410: "I can't call myself",
    411: "a teacher if I can't properly look after",
    412: "my students.",
    413: "...!",
    414: "I'll have you know, I still",
    415: "don't acknowledge you",
    416: "as my teacher!",
    417: "Excuse me?",
    418: "I-It was just a fluke! Normally",
    419: "I wouldn't show you such a pathetic",
    420: "sight!",
    421: "...Tch!",
    422: "Pupii!?",
    423: "H-Hey!",
    424: "▲!?",
    425: "Could it be...",
    426: "did I say something",
    427: "I shouldn't have???",
    428: "H-Huh?",
    429: "▲?",
    430: "Could it be...",
    431: "did I say something",
    432: "I shouldn't have?",
    433: "Whew...",
    434: "Watch your step.",
    435: "There may be something dangerous",
    436: "hidden in the undergrowth.",
    437: "Follow the path",
    438: "I take,",
    439: "okay?",
    440: "Follow the path",
    441: "I take,",
    442: "okay?",
    443: "I know.",
    444: "Meow!",
    445: "Hey...",
    446: "Hm?",
    447: "Yes?",
    448: "I'll thank you for yesterday,",
    449: "at least.",
    450: "Thanks.",
    451: "Ah, you don't have",
    452: "to worry about that.",
    453: "I promised, didn't I?",
    454: "I'd protect you",
    455: "no matter what.",
    456: "You're welcome.",
    457: "But you don't have",
    458: "to worry about that.",
    459: "I was only keeping",
    460: "my promise.",
    461: "...",
    462: "Besides, I'm",
    463: "your teacher.",
    464: "I can't call myself",
    465: "a teacher if I can't properly look after",
    466: "my students.",
    467: "Besides, I'm",
    468: "your teacher.",
    469: "I can't call myself",
    470: "a teacher if I can't properly look after",
    471: "my students.",
    472: "...I see.",
    473: "?",
    474: "No, never mind.",
    475: "It's nothing...",
    476: "Ugh...",
    477: "Watch your step.",
    478: "There may be something dangerous",
    479: "hidden in the undergrowth.",
}, 480: {
    480: "Follow the path",
    481: "I take,",
    482: "okay?",
    483: "Follow the path",
    484: "I take,",
    485: "okay?",
    486: "Understood.",
    487: "Bwee!",
    488: "Hey...",
    489: "Hm?",
    490: "Yes?",
    491: "I suppose I should say",
    492: "I appreciate what you did",
    493: "yesterday.",
    494: "Ah, you don't have",
    495: "to worry about that.",
    496: "I promised, didn't I?",
    497: "I'd protect you",
    498: "no matter what.",
    499: "You're welcome.",
    500: "But you don't have",
    501: "to worry about that.",
    502: "I was only keeping",
    503: "my promise.",
    504: "That's true, but...",
    505: "",
    506: "Besides, I'm",
    507: "your teacher.",
    508: "I can't call myself",
    509: "a teacher if I can't properly look after",
    510: "my students.",
    511: "Besides, I'm your",
    512: "teacher.",
    513: "I can't call myself",
    514: "a teacher if I can't properly look after",
    515: "my students.",
    516: "...!",
    517: "Y-You're right... When I",
    518: "think about it carefully, you, my servant,",
    519: "should naturally protect me!",
    520: "Huh?",
    521: "Well, keep",
    522: "working diligently at",
    523: "your duties from now on.",
    524: "Ah, how ridiculous!",
    525: "...Hmph!",
    526: "Bwee!?",
    527: "H-Hey!",
    528: "▲!?",
    529: "Could it be...",
    530: "did I say something",
    531: "I shouldn't have???",
    532: "H-Huh?",
    533: "▲?",
    534: "Could it be...",
    535: "did I say something",
    536: "I shouldn't have?",
    537: "Heave-ho.",
    538: "Watch your step.",
    539: "There may be something dangerous",
    540: "hidden in the undergrowth.",
    541: "Follow the path",
    542: "I take,",
    543: "okay?",
    544: "Follow the path",
    545: "I take,",
    546: "okay?",
    547: "Yes, Teacher.",
    548: "Kyu-py!",
    549: "U-Um...",
    550: "Hm?",
    551: "Thank you very much",
    552: "for helping me yesterday.",
    553: "",
    554: "Ah, you don't have",
    555: "to worry about that.",
    556: "I promised, didn't I?",
    557: "I'd protect you",
    558: "no matter what.",
    559: "You're welcome.",
}}


def draft(start):
    resource, rows, data = chapter_source(88)
    expected = set(range(start, start + 80))
    targets = TARGETS_BY_START.get(start)
    if targets is None or set(targets) != expected:
        raise ValueError("Target mapping must contain exactly the requested consecutive slice")
    translations = {}
    for number in sorted(expected):
        row = rows[number]
        source_text = data[row["source_offset"]:row["source_offset"] + row["source_byte_length"]].decode("cp932")
        text = targets[number]
        if control_tokens(source_text) != control_tokens(text):
            raise ValueError(f"Control token mismatch at resource row {number}")
        translations[row["id"]] = {
            "id": row["id"],
            "source_sha256": row["source_sha256"],
            "source_offset": row["source_offset"],
            "source_byte_length": row["source_byte_length"],
            "reference_instructions": row["reference_instructions"],
            "resource_row": number,
            "text": text,
            "status": "draft",
            "notes": "No source control tokens.",
        }
    return {
        "resource_id": resource["id"],
        "assigned_range": [start, start + 79],
        "rows_examined": {"ranges_inclusive": [[max(0, start - 20), start + 99]], "count": min(1711, start + 100) - max(0, start - 20)},
        "translations": translations,
        "uncertainties": [],
        "new_glossary_requests": [],
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--replace-existing", action="store_true")
    args = parser.parse_args()
    output = draft(args.start)
    directory = Path("work/translation/en/chapters_0.1.12/0088")
    destination = directory / f"slice_{args.start:04d}.targets.json"
    by_row = {value["resource_row"]: value for value in output["translations"].values()}
    print(json.dumps({
        "mode": "write" if args.write else "dry-run",
        "target": str(destination),
        "translation_count": len(output["translations"]),
        "samples": [by_row[row] for row in [args.start, args.start + 16, args.start + 41, args.start + 72, args.start + 79]],
    }, ensure_ascii=False, indent=2))
    if args.write:
        if destination.exists() and not args.replace_existing:
            raise FileExistsError(f"Refusing to overwrite existing target: {destination}")
        directory.mkdir(parents=True, exist_ok=True)
        destination.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
