"""English-only author draft for battle rows480-559; never self-accept."""
import sys
from battle_pass_055 import save

lines = [
    "on.", # 480; joins478-479 owned by adjacent author
    "Hah, then",
    "we just have to take out their leader!",
    "That's all well and good...",
    "Just make sure you",
    "don't go too far.",
    "Hey, calm down",
    "and listen to me, will you?",
    "Hey, calm down",
    "and listen to me!",
    "You're not going to",
    "fool me again!",
    "Hmm...",
    "I'll go easy on you,",
    "but I'm sorry if this hurts a little.",
    "Hmm...",
    "I'll go easy on you,",
    "but I'm sorry if this hurts a little, okay?",
    "Please stop",
    "copying me!",
    "You're the one who's copying me!",
    "That's cheating!",
    "I don't know what's going on,",
    "but it looks like we've got no choice",
    "but to beat them down!",
    "Fine by me...",
    "Come and get it!!",
    "I did talk big and say",
    "I'd look after things while Teacher was away.",
    "And I'm going to...",
    "keep that promise!!",
    "Pip-pip-peee!!",
    "I was rather full of myself",
    "when I said there was no need to worry.",
    "Now prove you meant it...",
    "Belfraw!!",
    "Bee-bee-beee!!",
    "I'm not confident that I can",
    "take Teacher's place...",
    "But!",
    "I will keep my promise!",
    "Kyupi-peee!!",
    "Right now, I'm the one",
    "responsible for protecting this island...",
    "I'll do Teacher's share as well",
    "and see this through!!",
    "Myaa-mya-mya!!",
    "All riiight!!",
    "Too bad for you...",
    "Come back when you're ready!",
    "Phew...",
    "I wonder if Teacher...",
    "will praise me?",
    "Whew...",
    "Perhaps we can manage after all?",
    "I'm worried about Kunon...",
    "She's capable, but",
    "something could still go wrong.",
    "Hmm...",
    "You two have gotten awfully close",
    "in such a short time, haven't you?",
    "Wh... What!?",
    "Don't be ridiculous!",
    "We know nothing about these enemies!",
    "They might carry some",
    "unknown poison...",
    "Everyone, be very careful!",
    "You got it!",
    "I wonder if Lady Misumi is all right?",
    "There's nothing to worry about!",
    "...That said,",
    "I'm sure a helping hand",
    "wouldn't go amiss.",
    "All right, let's give it our all!!",
    "Oh-ho-ho-ho!",
    "Monsters or not,",
    "I'll have them swooning",
    "over my sexy charms♪",
    "Having things like that fall for you",
    "is hardly a good thing...",
]

if __name__ == '__main__':
    save(480, lines, [(472,573)],
         uncertainties=[
             {'rows':[507,508], 'decision':'Teacher as absent person inferred from parallel student variants517-525; the source does not name the absent person in this box.'},
             {'rows':[514,515], 'decision':'Belfraw addresses herself by name as a self-challenge; same speaker operand22 in512-515, with her own boast in512-513.'},
             {'rows':[524,525], 'decision':'Teacher is the antecedent of the unnamed person, based on parallel517-520; no gender inferred.'},
         ], omissions=[],
         notes='Read complete VM groups at both edges. Row480 joins478-479 coordinated with author B. Restored subjects and verbs at box level, preserving nonempty fragment rows. Independent review required.',
         write='--write' in sys.argv)
