import argparse
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, str(Path(__file__).parent))

from chapter_source import chapter_source
from dialogue_encoding import control_tokens


TARGETS = {
    0: {
        0: "Mmm...",
        1: "I really",
        2: "slept well!",
        3: "or something.",
        4: "...Huh?",
        5: "It sounds like someone's outside,",
        6: "but...",
        7: "Yawn...",
        8: "It's morning...",
        9: "I slept well.",
        10: "Now then, let's do our best",
        11: "today too.",
        12: "...Huh?",
        13: "It sounds like someone's outside,",
        14: "but...",
        15: "Hnnngh...!",
        16: "Hah!",
        17: "Whew...!",
        18: "What, Teacher?",
        19: "You're up early.",
        20: "You're the one who's diligent, Kyle,",
        21: "training",
        22: "so early in the morning.",
        23: "You're the one who's amazing, Kyle,",
        24: "training",
        25: "so early in the morning.",
        26: "It's a habit, more or less.",
        27: "The person who taught me",
        28: "how to use this said",
        29: "the clear morning air",
        30: "is good for strengthening",
        31: "Stora's power.",
        32: "Stora...",
        33: "If I remember right, it was a healing method",
        34: "that uses the power of ki, wasn't it?",
        35: "Yeah, that's right.",
        36: "It can also increase your punching power",
        37: "and toughness.",
        38: "To tell you the truth,",
        39: "that's what I'm",
        40: "better at.",
        41: "Huh...",
        42: "Yes, that's right.",
        43: "I've studied it",
        44: "just a little.",
        45: "of it.",
        46: "I joined military school",
        47: "to study medicine,",
        48: "after all.",
        49: "Huh...",
        50: "Bro!",
        51: "Teacher!",
        52: "Breakfast is ready!",
        53: "Yeah, I'll be right there!",
        54: "Then I'll go",
        55: "wake ▲",
        56: "up.",
        57: "Then I'll go",
        58: "wake ▲",
        59: "up.",
        60: "Then I'll go",
        61: "wake ▲",
        62: "up.",
        63: "All right...",
        64: "Now that we've eaten,",
        65: "what should we do now?",
        66: "All right, then...",
        67: "Now that we've eaten,",
        68: "what should we do now?",
        69: "Even while we wait",
        70: "for the ship repairs to finish,",
        71: "it would be a waste",
        72: "to just sit around",
        73: "doing nothing until then.",
        74: "It would be a waste",
        75: "to just sit around",
        76: "doing nothing until then.",
        77: "...I know!",
        78: "Huh?",
        79: "Are you serious?",
    },
    80: {
        80: "What did you just",
        81: "say?",
        82: "Huh?!",
        83: "I said we'll start",
        84: "classes today,",
        85: "that's all.",
        86: "After all, I was hired",
        87: "as your private tutor.",
        88: "after all.",
        89: "So let's start",
        90: "our lessons.",
        91: "After all, I was hired",
        92: "as your private tutor.",
        93: "after all.",
        94: "After all, I was hired",
        95: "as your private tutor.",
        96: "after all.",
        97: "Things went off schedule a little,",
        98: "but you still need to study",
        99: "properly.",
        100: "Whaaat?!",
        101: "For one thing, I still",
        102: "don't recognize you",
        103: "as my teacher...",
        104: "Well, that's only natural,",
        105: "but...",
        106: "What you're saying",
        107: "is perfectly reasonable,",
        108: "but...",
        109: "I still haven't acknowledged",
        110: "that you're fit to be",
        111: "my teacher...",
        112: "That's right, isn't it?",
        113: "Ah, but...",
        114: "Look, paper and pens.",
        115: "I got them from",
        116: "Kyle and the others.",
        117: "Here, paper and pens.",
        118: "I got them from",
        119: "Kyle and the others.",
        120: "Ugh, I didn't",
        121: "ask...",
        122: "Hey!",
        123: "Listen when someone is talking...",
        124: "I'm putting together a textbook",
        125: "using a book we borrowed from Yard",
        126: "as a reference.",
        127: "I'll borrow Yard's book",
        128: "and have a textbook ready",
        129: "right away.",
        130: "We're all set♪",
        131: "Ugh...",
        132: "Huh...",
        133: "Well, you're",
        134: "prepared, aren't you?",
        135: "Oh...",
        136: "Ah, then",
        137: "that's fine.",
        138: "Let's see.",
        139: "Why don't we start",
        140: "with that?",
        141: "Um, what should",
        142: "we start with...?",
        143: "...Ah, right!",
        144: "Let's start",
        145: "with that.",
        146: "Huh? What?",
        147: "The basics of summoning.",
        148: "The basics of summoning.",
        149: "What...?",
        150: "Really?!",
        151: "Summoning...!",
        152: "Summoning...!",
        153: "Summoning...!",
        154: "What does ▲",
        155: "do you know about",
        156: "summoning?",
        157: "What does ▲",
        158: "do you know about",
        159: "summoning?",
    },
    160: {
        160: "What does ▲",
        161: "know about",
        162: "summoning?",
        163: "It's a way to call summoned beasts",
        164: "from another world and borrow",
        165: "their mysterious power, right?",
        166: "A technique that uses magic and spells to open",
        167: "a gate to another world, call its inhabitants,",
        168: "and command them.",
        169: "The method is called summoning;",
        170: "the user is a Summoner; those",
        171: "called are summoned beasts.",
        172: "A technique for calling summoned beasts",
        173: "through a gate opened with magic and spells",
        174: "and commanding them.",
        175: "A way to call beings living",
        176: "in another world and borrow",
        177: "their power... right?",
        178: "Yes, that's right.",
        179: "You know a lot.",
        180: "Yes, that's right.",
        181: "You know a lot.",
        182: "Heh heh, well...",
        183: "I've studied",
        184: "in my own way.",
        185: "That's just common sense",
        186: "to me.",
        187: "...",
        188: "Lyndbaum, where we live,",
        189: "borders four",
        190: "different worlds.",
        191: "Summoning",
        192: "uses magic, spells, and",
        193: "Summonite Stones",
        194: "to call summoned beasts",
        195: "from each world and",
        196: "borrow their power.",
        197: "Lyndbaum, where we live,",
        198: "borders four",
        199: "different worlds.",
        200: "Summoning, you see,",
        201: "uses magic, spells, and",
        202: "Summonite Stones",
        203: "to call summoned beasts",
        204: "from each world and",
        205: "borrow their power.",
        206: "Summonite Stones?",
        207: "Summonite Stones?",
        208: "Summonite Stones?",
        209: "Summonite Stones?",
        210: "Here, this is one.",
        211: "Here, this one.",
        212: "Huh, a little",
        213: "stone like this?",
        214: "This is one?",
        215: "It's my first time",
        216: "seeing a real one...",
        217: "It doesn't seem to be",
        218: "a gemstone.",
        219: "Its shape is uneven, too.",
        220: "Pretty...",
        221: "Each of these five-colored stones",
        222: "is a key that opens a door",
        223: "to another world.",
        224: "Each of these five-colored stones",
        225: "is a key that opens a door",
        226: "to another world.",
        227: "The black stone is Loreilal,",
        228: "a world entirely",
        229: "made by machines.",
        230: "Beep!",
        231: "Yes, that's right.",
        232: "It's the world you came from.",
        233: "Yes, exactly.",
        234: "It's the world you came from.",
        235: "Huh, is that so?",
        236: "The red stone is Silturn,",
        237: "a war-torn world where humans",
        238: "and yokai live together.",
        239: "Bwee-bwee!",
    },
    240: {
        240: "Yes, that's right.",
        241: "It's the world you came from.",
        242: "Yes, exactly.",
        243: "It's the world you came from.",
        244: "Oh, is that so?",
        245: "The purple stone is Sapureth,",
        246: "a world of angels, demons, and",
        247: "other spiritual beings.",
        248: "Kyu-py!",
        249: "Yes, that's right.",
        250: "It's the world you came from.",
        251: "Yes, exactly.",
        252: "It's the world you came from.",
        253: "Is that so?",
        254: "The green stone is Maetropa,",
        255: "a nature-rich world where",
        256: "demihumans live together.",
        257: "Meow, meow!",
        258: "Yes, that's right.",
        259: "It's the world you came from.",
        260: "Yes, exactly.",
        261: "It's the world you came from.",
        262: "I see...",
        263: "Then",
        264: "what world does this clear stone",
        265: "belong to?",
        266: "Then",
        267: "what world does this clear stone",
        268: "correspond to?",
        269: "Then",
        270: "what is this clear stone",
        271: "for?",
        272: "But there are",
        273: "five stones, aren't there?",
        274: "Nobody knows exactly",
        275: "what that clear stone",
        276: "is for.",
        277: "Nobody knows exactly",
        278: "what that clear stone is for.",
        279: "You can't call summoned beasts",
        280: "from the four worlds",
        281: "I just explained with it,",
        282: "but it is needed",
        283: "when using a completely different",
        284: "kind of summoning.",
        285: "For now, people say",
        286: "it's the key to a place called",
        287: "the Nameless World.",
        288: "It is needed",
        289: "when using a completely different",
        290: "kind of summoning.",
        291: "For now, people say",
        292: "it's the key to a place called",
        293: "the Nameless World.",
        294: "Hmm...",
        295: "I see...",
        296: "Hmm...",
        297: "I see...",
        298: "!",
        299: "Don't worry.",
        300: "The Summonite Stone",
        301: "is reacting to your magic.",
        302: "It's all right.",
        303: "The Summonite Stone",
        304: "is only reacting to your magic.",
        305: "It's all right.",
        306: "The Summonite Stone",
        307: "is only reacting to your magic.",
        308: "It seems Nup",
        309: "is compatible with",
        310: "Loreilal summoning.",
        311: "It seems Nup",
        312: "is compatible with",
        313: "Loreilal summoning.",
        314: "Really?!",
        315: "Can I call really cool",
        316: "mechanical soldiers?",
        317: "With enough practice.",
        318: "All right!",
        319: "Beep-beep!",
    },
    320: {
        320: "It seems Will",
        321: "is compatible with",
        322: "Maetropa summoning.",
        323: "It seems Will",
        324: "is compatible with",
        325: "Maetropa summoning.",
        326: "It's the most widely used",
        327: "kind of summoning.",
        328: "That's because it has",
        329: "so many uses.",
        330: "Well, the basics are important.",
        331: "Meow, meow!",
        332: "It seems Belfrau",
        333: "is compatible with",
        334: "Silturn summoning.",
        335: "It seems Belfrau",
        336: "is compatible with",
        337: "Silturn summoning.",
        338: "Silturn...",
        339: "It somehow sounds",
        340: "a little unsophisticated.",
        341: "That's not true.",
        342: "It's difficult to handle, but",
        343: "that makes it a deep kind of magic.",
        344: "That's not true.",
        345: "It's difficult to handle, but",
        346: "that makes it a deep kind of magic.",
        347: "R-Really?",
        348: "Does that mean",
        349: "I'm special?",
        350: "W-Well, I suppose.",
        351: "Hmm, you could",
        352: "say that.",
        353: "Hmm, is that so?",
        354: "Hee hee hee...",
        355: "Bwee-bwee!",
        356: "It seems Alieze",
        357: "is compatible with",
        358: "Sapureth summoning.",
        359: "It seems Alieze",
        360: "is compatible with",
        361: "Sapureth summoning.",
        362: "R-Really?",
        363: "Then can I call",
        364: "angels and such?!",
        365: "With enough practice.",
        366: "I'm so happy...",
        367: "I've always",
        368: "dreamed of that!",
        369: "Kyu-py!",
        370: "I'll teach you the concrete steps",
        371: "and necessary skills",
        372: "little by little from now on.",
        373: "All right, that's",
        374: "all for today's",
        375: "lesson.",
        376: "I'll teach you the concrete steps",
        377: "and necessary skills",
        378: "little by little from now on.",
        379: "All right,",
        380: "that's all for today's lesson.",
        381: "Yes?",
        382: "Oh, there you are!",
        383: "Can I have a word?",
        384: "What is it?",
        385: "We're going to talk",
        386: "about what comes next,",
        387: "so gather in the captain's cabin.",
        388: "All right...",
        389: "I asked you to gather",
        390: "so we could explain",
        391: "our situation to",
        392: "our new guests.",
        393: "...",
        394: "...",
        395: "...",
        396: "...",
        397: "You already know why",
        398: "we targeted that ship,",
        399: "don't you?",
    },
    400: {
        400: "The sword, right?",
        401: "The sword",
        402: "I'm holding now, right?",
        403: "The sword",
        404: "I'm holding now, right?",
        405: "Yes.",
        406: "I'm sure you understand better than anyone",
        407: "now that you hold it yourself,",
        408: "but that sword is no ordinary",
        409: "sword.",
        410: "It is one of two swords",
        411: "kept under strict guard",
        412: "by an organization,",
        413: "an item that seals great magic",
        414: "and knowledge.",
        415: "Why was a sword like that",
        416: "on that ship?!",
        417: "Why was such an incredible sword",
        418: "on that ship",
        419: "in the first place?",
        420: "You said it was under",
        421: "strict guard...",
        422: "Well...",
        423: "Yard stole it.",
        424: "This Yard did.",
        425: "What?!",
        426: "What?!",
        427: "Huh?!",
        428: "That means...",
        429: "S-Stolen...",
        430: "Why...?",
        431: "The Colorless Faction...",
        432: "Have you heard",
        433: "that name before?",
        434: "That's...",
        435: "Don't know",
        436: "Know it",
        437: "They're crazy people",
        438: "carrying out destructive acts",
        439: "all over the continent.",
        440: "They spout nonsense about making",
        441: "a country where Summoners are supreme,",
        442: "they say.",
        443: "I've heard of them.",
        444: "They're a group of Summoners",
        445: "that is hostile to",
        446: "every government, right...?",
        447: "I used to belong",
        448: "to the Colorless Faction.",
        449: "!?",
        450: "That sword was",
        451: "to be used as a vital key",
        452: "in a new Colorless Faction",
        453: "operation.",
        454: "That was the plan.",
        455: "Well, after various things happened,",
        456: "Yard decided to leave",
        457: "the Faction.",
        458: "So... by taking the sword,",
        459: "he planned to stop",
        460: "that operation.",
        461: "I see...",
        462: "But during the struggle",
        463: "with the pursuers, the sword",
        464: "left my hands",
        465: "and was recovered",
        466: "by the Imperial Army.",
        467: "Well, I don't think Teacher",
        468: "noticed, but",
        469: "that ship had soldiers",
        470: "transporting the sword",
        471: "in secret.",
        472: "So those people we saw",
        473: "in the hold were them?",
        474: "Were those people we saw",
        475: "in the hold them?",
        476: "Once we heard the circumstances,",
        477: "our family decided",
        478: "to lend a hand.",
        479: "We would take back the sword",
    },
    480: {
        480: "and throw it away somewhere",
        481: "where no one can get at it.",
        482: "That's why",
        483: "we attacked that ship.",
        484: "What the hell is that?!",
        485: "So we just",
        486: "got caught up",
        487: "in this?!",
        488: "So...",
        489: "we went through all this",
        490: "because of that person's mistake?",
        491: "You attacked us,",
        492: "didn't you?!",
        493: "Because of that,",
        494: "I've been through",
        495: "so much...",
        496: "I understand the circumstances.",
        497: "But...",
        498: "This is awful!",
        499: "So we were just",
        500: "dragged into this?!",
        501: "I truly am",
        502: "sorry...",
        503: "Saying sorry",
        504: "doesn't make it all right!",
        505: "B-Beep...",
        506: "Take us home!",
        507: "Right now...!",
        508: "U-Ugh...",
        509: "Kyuu...",
        510: "▲",
        511: "Come on, calm down.",
        512: "▲",
        513: "Calm down, okay?",
        514: "▲",
        515: "Calm down, okay?",
        516: "But...!",
        517: "But...!",
        518: "I know it feels",
        519: "unfair, but",
        520: "blaming someone",
        521: "who's apologizing won't",
        522: "change reality.",
        523: "I know it feels",
        524: "impossible to accept.",
        525: "But blaming someone",
        526: "who's apologizing won't",
        527: "change reality, right?",
        528: "Ugh...",
        529: "Ugh...",
        530: "More importantly,",
        531: "it's important to think about",
        532: "what we do from here, right?",
        533: "More importantly,",
        534: "we need to think about",
        535: "what we do from here.",
        536: "Right?",
        537: ".......",
        538: ".......",
        539: "I'm not going to",
        540: "make excuses...",
        541: "...!",
        542: "...!",
        543: "I'm not going to",
        544: "make excuses...",
        545: "The boy's right.",
        546: "The young lady's",
        547: "right.",
        548: "I'll take responsibility",
        549: "for this. I will",
        550: "take you home, no matter what.",
        551: "So please endure",
        552: "a little longer.",
        553: "I beg you...",
        554: "!?",
        555: "!?",
        556: "!?",
        557: "!?",
        558: "Please raise your head,",
        559: "Kyle...",
    },
    560: {
        560: "...All right.",
        561: "...All right.",
        562: "...Very well.",
        563: "...All right.",
        564: "▲...",
        565: "▲...",
        566: "▲...",
        567: "▲...",
        568: "▲...",
        569: "It's a promise",
        570: "between men, okay?",
        571: "If you break",
        572: "that promise, I won't forgive you...",
        573: "You did well",
        574: "holding back just now, didn't you?",
        575: "▲",
        576: "You did well",
        577: "holding back just now,",
        578: "▲.",
        579: "You did well",
        580: "holding back just now,",
        581: "▲.",
        582: "It's nothing...",
        583: "I just thought",
        584: "complaining wouldn't",
        585: "accomplish anything.",
        586: "It's nothing...",
        587: "Listen.",
        588: "Even I understand",
        589: "there's no point",
        590: "in blaming those people!",
        591: "No...",
        592: "I'm the one who",
        593: "lost control.",
        594: "How embarrassing...",
        595: "I see...",
        596: "W-What?!",
        597: "What are you laughing at?",
        598: "W-What?!",
        599: "Don't smirk at me!",
        600: "......",
        601: "Hmm...",
        602: "How is it,",
        603: "really?",
        604: "How is it,",
        605: "really?",
        606: "No, the ship's damage",
        607: "itself isn't all that",
        608: "serious.",
        609: "The problem is manpower",
        610: "and materials for repairs.",
        611: "Oh...",
        612: "We can search the island",
        613: "for materials, but",
        614: "it's the manpower",
        615: "that makes things take",
        616: "that much longer.",
        617: "But as long as we have time,",
        618: "we can manage",
        619: "somehow, right?",
        620: "Yeah, probably.",
        621: "Then let's take it",
        622: "slowly and steadily.",
        623: "I'll help too",
        624: "however I can.",
        625: "Then let's take it",
        626: "slowly and steadily.",
        627: "I'll help too",
        628: "however I can.",
        629: "...You're right.",
        630: "Let's give it",
        631: "a try for now!",
        632: "Yeah!",
        633: "Yes!",
        634: "I'm surprised",
        635: "Bro would bow",
        636: "like that.",
        637: "Yeah...",
        638: "Is that so?",
        639: "Yeah, he usually",
    },
    640: {
        640: "laughs off",
        641: "most things.",
        642: "When things get troublesome,",
        643: "he tends to solve everything",
        644: "by force, too...",
        645: "Ha ha ha...",
        646: "Our family",
        647: "is in its third generation",
        648: "under Bro Kyle.",
        649: "We've always stuck to",
        650: "not being needlessly cruel",
        651: "as a rule.",
        652: "That's probably why he felt",
        653: "so bad about dragging Teacher",
        654: "and the others into this...",
        655: "But we can't have him",
        656: "worrying forever,",
        657: "so I hope",
        658: "we can take it",
        659: "a little easier from now on,",
        660: "okay?",
        661: "But we can't have him",
        662: "worrying forever,",
        663: "either.",
        664: "I hope we can take it",
        665: "a little easier",
        666: "from now on, okay?",
        667: "Yeah, that's right.",
        668: "I'm sorry.",
        669: "I wasn't considerate enough.",
        670: "Please don't worry.",
        671: "I'm sure that child",
        672: "understands, too.",
        673: "That it isn't anyone's fault.",
        674: "●...",
        675: "....",
        676: "Still, Teacher",
        677: "really brought things together",
        678: "for us. That helped.",
        679: "This one has always",
        680: "been bad at handling things.",
        681: "Hey, Scarrel!",
        682: "That has nothing",
        683: "to do with the past!",
        684: "Have you two known",
        685: "each other for a long time?",
        686: "Well, sort of.",
        687: "When we were little,",
        688: "a bit.",
        689: "But I never imagined",
        690: "we'd run into each other again",
        691: "in an alley.",
        692: "Huh?",
        693: "Scarrel happened to find me",
        694: "when I had collapsed",
        695: "on the street.",
        696: "That led to me",
        697: "being taken in",
        698: "by Kyle's family.",
        699: "Well, you could call it",
        700: "a fated connection.",
        701: "Huh...",
        702: "Is that so...?",
        703: "A fishing rod",
        704: "in a place like this...",
        705: "Oh, a fishing rod",
        706: "in a place like this...",
        707: "But whose is it?",
        708: "Oh, that's for emergencies.",
        709: "Emergencies?",
        710: "For gathering food",
        711: "when the need arises,",
        712: "we keep it on the ship.",
        713: "We've never been forced",
        714: "into a situation to use it,",
        715: "so it's practically brand new.",
        716: "That seems",
        717: "kind of wasteful...",
        718: "That does seem",
        719: "a little wasteful,",
    },
    720: {
        720: "though...",
        721: "If you think so,",
        722: "go ahead and use it.",
        723: "...Is that okay?",
        724: "Huh, really?",
        725: "Sure. As long as you",
        726: "put it back where it was,",
        727: "use it as you like.",
        728: "And if you can secure",
        729: "some food while you're at it,",
        730: "that would help a lot!",
        731: "I see, then...",
        732: "What should we do...?",
        733: "Go fishing",
        734: "Leave it alone",
        735: "Survey the island?",
        736: "Yeah, while looking for",
        737: "materials we need for repairs.",
        738: "To avoid dangers",
        739: "like last time,",
        740: "we should learn",
        741: "at least a little",
        742: "about this island.",
        743: "Maybe there's treasure",
        744: "or something, too?",
        745: "No way...",
        746: "But if we're surveying it,",
        747: "where will we start",
        748: "from?",
        749: "This island is",
        750: "pretty big...",
        751: "This island looks",
        752: "pretty large.",
        753: "It isn't a small island",
        754: "we can circle easily.",
        755: "This island",
        756: "is very large...",
        757: "About that...",
        758: "When we washed up here,",
        759: "we saw something like lights",
        760: "from out at sea.",
        761: "Lights?",
        762: "Lights?",
        763: "Yeah, four of them,",
        764: "like they surrounded",
        765: "the center of the island.",
        766: "Could that",
        767: "possibly mean...",
        768: "Y-Yeah, maybe",
        769: "there are people living",
        770: "on this island?",
        771: "If there are, we'll talk to them",
        772: "and ask them to share",
        773: "materials needed for repairs.",
        774: "So you won't call it",
        775: "plundering?",
        776: "▲!?",
        777: "▲!?",
        778: "...",
        779: "The question is",
        780: "which of the four places",
        781: "we visit first.",
        782: "My gut says the red light",
        783: "flickering at the front right",
        784: "is the real deal.",
        785: "Come on, Bro's intuition",
        786: "isn't reliable!",
        787: "I think the purple light at the front left",
        788: "is the one, because",
        789: "it was sparkling...",
        790: "If you're talking about shining, the blue light",
        791: "at the back right looked like",
        792: "it was blinking, too.",
        793: "Then I'll recommend",
        794: "the green light at the back left,",
        795: "just because...",
        796: "Your opinions are",
        797: "all over the place!",
        798: "What is wrong",
        799: "with these people...?",
    }
}


def draft(start):
    resource, rows, data = chapter_source(111)
    expected = set(range(start, start + 80))
    targets = TARGETS.get(start)
    if targets is None or set(targets) != expected:
        raise ValueError("Target mapping must contain exactly the requested consecutive slice")
    translations = {}
    for number in sorted(expected):
        row = rows[number]
        source_text = data[row["source_offset"]:row["source_offset"] + row["source_byte_length"]].decode("cp932")
        text = targets[number]
        if control_tokens(source_text) != control_tokens(text):
            raise ValueError(f"Control token mismatch at resource row {number}")
        translations[row["id"]] = {
            "id": row["id"], "source_sha256": row["source_sha256"],
            "source_offset": row["source_offset"], "source_byte_length": row["source_byte_length"],
            "reference_instructions": row["reference_instructions"], "resource_row": number,
            "text": text, "status": "draft", "notes": "Control tokens preserved." if control_tokens(source_text) else "No source control tokens.",
        }
    return {
        "resource_id": resource["id"], "assigned_range": [start, start + 79],
        "rows_examined": {"ranges_inclusive": [[max(0, start - 20), start + 99]], "count": min(len(rows), start + 100) - max(0, start - 20)},
        "translations": translations, "uncertainties": [], "new_glossary_requests": [],
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--replace-existing", action="store_true")
    args = parser.parse_args()
    output = draft(args.start)
    directory = Path("work/translation/en/chapters_0.1.12/0111")
    destination = directory / f"slice_{args.start:04d}.targets.json"
    by_row = {value["resource_row"]: value for value in output["translations"].values()}
    print(json.dumps({"mode": "write" if args.write else "dry-run", "target": str(destination), "translation_count": len(output["translations"]), "samples": [by_row[row] for row in [args.start, args.start + 16, args.start + 41, args.start + 72, args.start + 79]]}, ensure_ascii=False, indent=2))
    if args.write:
        if destination.exists() and not args.replace_existing:
            raise FileExistsError(f"Refusing to overwrite existing target: {destination}")
        directory.mkdir(parents=True, exist_ok=True)
        destination.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
