"""Record Chapter 8 authorship checks without claiming independent review."""
import json,hashlib,sys
from pathlib import Path
import chapter_patch_014 as c
from chapter_source_014 import ROOT
folder=ROOT/'work/translation/en/chapters_0.1.14/0226'
paths=sorted(folder.glob('slice_*.targets.json'))
rows=sorted(t['resource_row'] for p in paths for t in json.loads(p.read_text(encoding='utf-8'))['translations'].values())
assert rows==list(range(3003))
report={'version':'0.1.14','resource_id':'00:00226','scope':'Chapter 8 main-tail only','assigned_relative_range':[0,3002],'physical_range':[3957,6959],'rows_in_scope':3003,'rows_authored':3003,'unique_source_rows_examined':3011,'examined_physical_range':[3949,6959],'slice_count':38,'review_status':'translator_self_review_only','independent_semantic_review':False,'method':'Translated directly from Japanese source in consecutive 80-row slices with neighboring context. No machine translation service. Full meaning drafted before compiler wrapping. Author checked meaning while drafting and inspected terminology/menu corrections after drafting. No claim of a second independent full-pass review.','validation':{'source_identity_hash_offset_length_references':'passed','control_tokens_and_cp932_encoding':'passed','tail_only_draft_compiler':'passed','groups':1468,'pages':1630,'all_group_calls_simulated':True,'live_pool_text_preserved':True,'unrelated_code_preserved':True,'main_tail_remaining_rows':0,'full_resource_preview':'Initially blocked by shared-prefix row 0 width, outside this assignment; tail-only compiler passed.'},'resolved_terminology':['Primary SN6 gallery character names','The Qualified','inherit/inheritance','Shartos','Crissles, the Crimson Tyrant','Veiger','Yukres Village','Land of Wind and Thunder'],'remaining_uncertainties':['Gate of Evocation remains provisional project term.','Rikuto remains provisional researched romanization.','Chuur is a provisional fairy-tale name; gender unknown, neutral wording used.','Oni Princess of the Summer Wind is a provisional descriptive title.','The dream warning about being swallowed by a Guardian is interrupted and ambiguous in source; ambiguity retained.','Marurur descriptive nicknames preserved; Mr. Stripes agrees with older project usage.','No emulator/UI visual check performed.'],'draft_inputs_sha256':{str(p.relative_to(ROOT)).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},'notes':'Slice-level uncertainty notes record drafting-time provisional decisions; this report lists the final resolved terminology. English staging draft JSON files are not compiler inputs; slice_*.targets.json files are authoritative.'}
print(json.dumps({k:v for k,v in report.items() if k!='draft_inputs_sha256'},indent=2))
if '--write' in sys.argv:(folder/'translator_self_review.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
